upstream choezy_app {
    server unix:/run/choezy/gunicorn.sock fail_timeout=0;
}

server {
    listen 80;
    listen [::]:80;
    server_name _;

    client_max_body_size 10M;

    location /static/ {
        alias /srv/choezy/staticfiles/;
        access_log off;
        expires 7d;
    }

    location /media/ {
        alias /srv/choezy/media/;
        access_log off;
        expires 7d;
    }

    location / {
        proxy_pass http://choezy_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 60s;
        proxy_read_timeout 60s;
    }
}
