# Generated by Django 6.0.7 on 2026-07-29 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alternatives', '0002_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose_fit', models.CharField(choices=[('HIGH', '높음'), ('MIDDLE', '중간'), ('LOW', '낮음')], max_length=10)),
                ('expected_satisfaction', models.CharField(choices=[('HIGH', '높음'), ('MIDDLE', '중간'), ('LOW', '낮음')], max_length=10)),
                ('recommendation', models.CharField(choices=[('HIGH', '높음'), ('MIDDLE', '중간'), ('LOW', '낮음')], max_length=10)),
                ('summary', models.TextField()),
                ('ai_model', models.CharField(blank=True, max_length=100)),
                ('consideration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='products.consideration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinalChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choice_type', models.CharField(choices=[('PRODUCT', '상품 구매'), ('ALTERNATIVE', '대안 선택'), ('POSTPONE', '보류')], max_length=20)),
                ('memo', models.TextField(blank=True)),
                ('decided_on', models.DateField()),
                ('alternative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_choices', to='alternatives.alternative')),
                ('consideration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_choice', to='products.consideration')),
            ],
        ),
        migrations.CreateModel(
            name='SpendingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spent_on', models.DateField()),
                ('category', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField()),
                ('final_choice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spending_record', to='analyses.finalchoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spending_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-spent_on', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='finalchoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('alternative__isnull', False), ('choice_type', 'ALTERNATIVE')), models.Q(('alternative__isnull', True), ('choice_type__in', ['PRODUCT', 'POSTPONE'])), _connector='OR'), name='valid_final_choice_alternative'),
        ),
        migrations.AddIndex(
            model_name='spendingrecord',
            index=models.Index(fields=['user', 'spent_on'], name='spending_user_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='spendingrecord',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='spending_amount_gt_0'),
        ),
    ]
