# Generated by Django 6.0.7 on 2026-07-29 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alternatives', '0003_alternative_valid_alternative_result'),
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalchoice',
            name='alternative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='final_choices', to='alternatives.alternative'),
        ),
    ]
