# Generated by Django 6.0.7 on 2026-08-08 03:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0002_alter_finalchoice_alternative'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='key_points',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list),
        ),
        migrations.AddConstraint(
            model_name='decision',
            constraint=models.CheckConstraint(condition=models.Q(('key_points__len__lte', 3)), name='decision_key_points_max_count'),
        ),
    ]
