# Generated by Django 6.0.7 on 2026-08-10 14:16

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def copy_purchase_date_to_recorded_on(apps, schema_editor):
    SpendingRecord = apps.get_model("analyses", "SpendingRecord")
    SpendingRecord.objects.filter(recorded_on__isnull=True).update(
        recorded_on=models.F("purchased_on")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0003_decision_key_points_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spendingrecord",
            options={"ordering": ["-recorded_on", "-created_at"]},
        ),
        migrations.RemoveConstraint(
            model_name="spendingrecord", name="spending_amount_gt_0",
        ),
        migrations.RemoveIndex(
            model_name="spendingrecord", name="spending_user_date_idx",
        ),
        migrations.RenameField(
            model_name="spendingrecord", old_name="item_name", new_name="product_name",
        ),
        migrations.RenameField(
            model_name="spendingrecord", old_name="amount", new_name="product_price",
        ),
        migrations.RenameField(
            model_name="spendingrecord",
            old_name="spent_on",
            new_name="purchased_on",
        ),
        migrations.AlterField(
            model_name="spendingrecord",
            name="purchased_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="spendingrecord",
            name="image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="spendingrecord",
            name="product_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="spendingrecord",
            name="purchase_status",
            field=models.CharField(
                choices=[
                    ("PURCHASED", "구매 확정"),
                    ("DEFERRED", "구매 보류"),
                    ("NOT_PURCHASED", "구매 안 함"),
                ],
                default="PURCHASED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="spendingrecord",
            name="recorded_on",
            field=models.DateField(null=True),
        ),
        migrations.RunPython(
            copy_purchase_date_to_recorded_on,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="spendingrecord",
            name="recorded_on",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name="spendingrecord",
            name="satisfaction",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="spendingrecord",
            index=models.Index(
                fields=["user", "recorded_on"], name="spending_user_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="spendingrecord",
            index=models.Index(
                fields=["user", "purchase_status"], name="spending_user_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="spendingrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("product_price__gt", 0)),
                name="spending_product_price_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="spendingrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("satisfaction__isnull", True),
                    ("satisfaction__range", (1, 5)),
                    _connector="OR",
                ),
                name="spending_satisfaction_1_to_5",
            ),
        ),
        migrations.AddConstraint(
            model_name="spendingrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("purchase_status", "PURCHASED"),
                        ("purchased_on__isnull", False),
                    ),
                    models.Q(
                        ("purchase_status__in", ["DEFERRED", "NOT_PURCHASED"]),
                        ("purchased_on__isnull", True),
                        ("satisfaction__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="spending_status_fields_consistent",
            ),
        ),
    ]
