# Generated by Django 6.0.7 on 2026-08-10 14:26

import django.db.models.deletion
from django.db import migrations, models


def connect_existing_records(apps, schema_editor):
    SpendingRecord = apps.get_model("analyses", "SpendingRecord")
    for record in SpendingRecord.objects.filter(
        consideration__isnull=True,
        final_choice__isnull=False,
    ).select_related("final_choice"):
        record.consideration_id = record.final_choice.consideration_id
        record.save(update_fields=["consideration"])


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0004_alter_spendingrecord_options_and_more"),
        ("products", "0003_consideration_product_assessment"),
    ]

    operations = [
        migrations.AddField(
            model_name="spendingrecord",
            name="consideration",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="spending_record",
                to="products.consideration",
            ),
        ),
        migrations.RunPython(
            connect_existing_records,
            migrations.RunPython.noop,
        ),
    ]
