# Generated by Django 6.0.7 on 2026-08-10 15:58

import django.contrib.postgres.fields
from django.conf import settings
from django.db import migrations, models


def backfill_historical_snapshots(apps, schema_editor):
    SpendingRecord = apps.get_model("analyses", "SpendingRecord")
    records = SpendingRecord.objects.select_related(
        "consideration",
        "user",
    )
    for record in records.iterator():
        changed_fields = []
        if record.consideration_id is not None:
            consideration = record.consideration
            record.purpose_snapshot = consideration.purpose
            record.purpose_detail_snapshot = consideration.purpose_detail
            record.compare_criteria_snapshot = list(
                consideration.compare_criteria
            )
            changed_fields.extend(
                [
                    "purpose_snapshot",
                    "purpose_detail_snapshot",
                    "compare_criteria_snapshot",
                ]
            )
        record.monthly_budget_snapshot = record.user.monthly_budget
        changed_fields.append("monthly_budget_snapshot")
        record.save(update_fields=changed_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0005_spendingrecord_consideration"),
        ("products", "0003_consideration_product_assessment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="spendingrecord",
            name="budget_amount_snapshot",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="spendingrecord",
            name="compare_criteria_snapshot",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=30), blank=True, default=list
            ),
        ),
        migrations.AddField(
            model_name="spendingrecord",
            name="monthly_budget_snapshot",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="spendingrecord",
            name="purpose_detail_snapshot",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="spendingrecord",
            name="purpose_snapshot",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.RunPython(
            backfill_historical_snapshots,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="spendingrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("budget_amount_snapshot__isnull", True),
                    ("budget_amount_snapshot__gt", 0),
                    _connector="OR",
                ),
                name="spending_budget_snapshot_gt_0",
            ),
        ),
    ]
