# Generated by Django 6.0.7 on 2026-07-31 11:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_email"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE accounts_user
                        ALTER COLUMN spending_type TYPE varchar(20)[]
                        USING CASE
                            WHEN spending_type = '' THEN ARRAY[]::varchar(20)[]
                            ELSE ARRAY[spending_type]::varchar(20)[]
                        END;
                    """,
                    reverse_sql="""
                        ALTER TABLE accounts_user
                        ALTER COLUMN spending_type TYPE varchar(20)
                        USING COALESCE(spending_type[1], '');
                    """,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="user",
                    name="spending_type",
                    field=django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("VALUE", "가성비 중시"),
                                ("QUALITY", "품질 중시"),
                                ("EXPERIENCE", "경험·만족 중시"),
                                ("GROWTH", "자기계발 중시"),
                                ("ASSET", "자산 형성 중시"),
                                ("CAUTIOUS", "신중한 소비 중시"),
                            ],
                            max_length=20,
                        ),
                        blank=True,
                        default=list,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="value_criteria",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("PRICE", "가격"),
                        ("SATISFACTION", "만족도"),
                        ("QUALITY", "품질·성능"),
                        ("UTILIZATION", "활용도"),
                        ("DURATION", "지속·유지 기간"),
                        ("EFFICIENCY", "효율성"),
                    ],
                    max_length=30,
                ),
                blank=True,
                default=list,
            ),
        ),
    ]
