# Generated by Django 6.0.7 on 2026-07-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.PositiveSmallIntegerField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('unit_price', models.PositiveIntegerField()),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('expected_effect', models.TextField(blank=True)),
                ('ai_reason', models.TextField(blank=True)),
                ('result_type', models.CharField(choices=[('QUANTITY', '수량 환산'), ('FUTURE_VALUE', '미래가치')], max_length=20)),
                ('equivalent_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('future_value', models.PositiveIntegerField(blank=True, null=True)),
                ('display_text', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['category__display_order', 'slot', '-version'],
            },
        ),
        migrations.CreateModel(
            name='AlternativeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('unit_label', models.CharField(blank=True, max_length=30)),
                ('average_price', models.PositiveIntegerField()),
                ('spec_note', models.CharField(blank=True, max_length=300)),
                ('calc_type', models.CharField(choices=[('UNIT_PRICE', '단가 환산'), ('SAVINGS', '적금'), ('DEPOSIT', '예금'), ('INVESTMENT', '투자')], default='UNIT_PRICE', max_length=20)),
                ('calc_params', models.JSONField(blank=True, default=dict)),
                ('source_name', models.CharField(max_length=200)),
                ('source_url', models.URLField(max_length=500)),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category__display_order', 'name', '-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('TRAVEL', '여행'), ('HEALTH', '운동(건강)'), ('CULTURE', '문화(여가)'), ('LIVING', '생활편의'), ('DIGITAL', '디지털 전자기기'), ('FINANCE', '재정')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LLMRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('GENERATE', '최초 생성'), ('REGENERATE', '개별 재생성'), ('DECISION', '구매 의사결정')], max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('prompt', models.TextField()),
                ('response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', '성공'), ('FAILED', '실패')], max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
