# Generated by Django 6.0.7 on 2026-07-29 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alternatives', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternative',
            name='consideration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='products.consideration'),
        ),
        migrations.AddField(
            model_name='alternative',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alternatives', to='alternatives.alternativeitem'),
        ),
        migrations.AddField(
            model_name='alternativeitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alternative_items', to='alternatives.category'),
        ),
        migrations.AddField(
            model_name='alternative',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alternatives', to='alternatives.category'),
        ),
        migrations.AddField(
            model_name='llmrequestlog',
            name='consideration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_request_logs', to='products.consideration'),
        ),
        migrations.AddIndex(
            model_name='alternativeitem',
            index=models.Index(fields=['category', 'is_active'], name='alt_item_category_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='alternativeitem',
            constraint=models.CheckConstraint(condition=models.Q(('average_price__gt', 0)), name='alternative_item_price_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='alternative',
            constraint=models.CheckConstraint(condition=models.Q(('slot__gte', 1), ('slot__lte', 3)), name='alternative_slot_between_1_and_3'),
        ),
        migrations.AddConstraint(
            model_name='alternative',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='alternative_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='alternative',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gt', 0)), name='alternative_unit_price_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='alternative',
            constraint=models.UniqueConstraint(fields=('consideration', 'category', 'slot', 'version'), name='unique_alternative_slot_version'),
        ),
        migrations.AddConstraint(
            model_name='alternative',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('consideration', 'category', 'slot'), name='unique_current_alternative_slot'),
        ),
    ]
