# Generated by Django 6.0.7 on 2026-07-29 12:25

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alternatives', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consideration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.PositiveIntegerField()),
                ('product_features', models.TextField(blank=True)),
                ('product_url', models.URLField(blank=True, max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('purpose', models.CharField(choices=[('DEVELOPMENT', '개발/업무'), ('DESIGN', '디자인/창작'), ('STUDY', '공부'), ('HOBBY', '취미'), ('TRAVEL_RECORD', '여행 기록'), ('ETC', '기타')], max_length=30)),
                ('purpose_detail', models.CharField(blank=True, max_length=200)),
                ('compare_criteria', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PRICE', '가격'), ('DURATION', '지속 가능 기간'), ('EXPECTED_EFFECT', '기대 효과'), ('AVAILABLE_BUDGET', '가용 예산')], max_length=30), blank=True, default=list)),
                ('status', models.CharField(choices=[('DRAFT', '작성 중'), ('GENERATED', '대안 생성 완료'), ('DECIDED', '선택 완료'), ('CLOSED', '종료')], default='DRAFT', max_length=20)),
                ('categories', models.ManyToManyField(blank=True, related_name='considerations', to='alternatives.category')),
                ('exclude_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='excluded_considerations', to='alternatives.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='considerations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('product_price__gt', 0)), name='consideration_product_price_gt_0')],
            },
        ),
    ]
