# Generated by Django 6.0.7 on 2026-08-03 06:23

from django.db import migrations, models


def migrate_purpose_values(apps, schema_editor):
    Consideration = apps.get_model("products", "Consideration")
    mappings = {
        "DEVELOPMENT": "WORK",
        "STUDY": "SELF_DEVELOPMENT",
        "TRAVEL_RECORD": "TRAVEL",
    }
    for old_value, new_value in mappings.items():
        Consideration.objects.filter(purpose=old_value).update(purpose=new_value)


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(migrate_purpose_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="consideration",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("SELF_DEVELOPMENT", "자기계발"),
                    ("TRAVEL", "여행"),
                    ("DESIGN", "디자인"),
                    ("GIFT", "선물"),
                    ("WORK", "업무"),
                    ("HOBBY", "취미·여가"),
                    ("CONVENIENCE", "일상 편의"),
                    ("ETC", "기타"),
                ],
                max_length=30,
            ),
        ),
    ]
